### PR TITLE
Tc check

### LINKED ISSUE #351: Implement CHECK macros as exceptions
At the moment we have too many places where we call one of the glog CHECK macros and terminate when it fails.
Let's implement our own CHECK macros and recover when it makes sense.
@salexspb @Yangqing I know C2 has its way of dealing with this, could you offer some guidance on what would make the most sense wrt FB infra?

Assigning to @ttheodor since we discussed about this last month.

### PR DESCRIPTION
**Pull request by ttheodor**
closes #351

### CODE REVIEW

**Comment by skimo-openhub** [comment]
On Tue, May 29, 2018 at 08:37:19AM -0700, Theodoros Theodoridis wrote:
> closes #351 

I haven't looked at it in detail yet, but this looks great.

skimo

File: tc/core/check.cc [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+  if (not additionalMsg_.empty()) {
+    ss << ": " << additionalMsg_;
+  }
+  throw std::runtime_error(ss.str());
+}
+
+Checker tc_check(bool condition, const char* filename, uint64_t lineno) {
+  if (condition) {
+    return Checker(condition, {}, {});
+  }
```
Comment (skimo-openhub) [inline tc/core/check.cc]: Why this special case?  Is it to avoid calling `makeLocation`?
Why not simply store `filename` and `lineno`?
Also, why does only this variant have such a special case?

File: tc/core/check.h [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+      additionalMsg_.pop_back();
+    }
+    return *this;
+  }
+
+ private:
+  bool condition_;
+  std::string location_;
+  std::string baseErrorMsg_;
+  std::string additionalMsg_;
```
Comment (skimo-openhub) [inline tc/core/check.h]: Why do you need to make a distinction between these two types of messages?

File: test/test_check.cc [hunk 3]
```diff
@@ -0,0 +1,177 @@
...
+    std::stringstream expected;
+    expected << "Check failed [" << __FILE__ << ':' << __LINE__ + 2 << ']'
+             << ": 1+1=3";
+    ASSERT_THROW_WHAT(TC_CHECK(false) << "1+1=3", expected.str());
+  }
+}
+
+TEST(CHECK, Vector) {
+  std::stringstream expected;
+  expected << "Check failed [" << __FILE__ << ':' << __LINE__ + 3 << ']'
```
Comment (skimo-openhub) [inline test/test_check.cc]: This looks fragile and probably compiler dependent.
Why can you assume that the reported line number is the last line of
the macro invocation?  Better make sure `ASSERT_THROW_WHAT` call
is within a single line in these tests.

File: test/test_check.cc [hunk 4]
```diff
@@ -0,0 +1,177 @@
...
+  }
+}
+
+TEST(CHECK, LT) {
+  ASSERT_NO_THROW(TC_CHECK_LT(1, 2));
+  ASSERT_NO_THROW(TC_CHECK_LT(std::string("aaa"), std::string("baa")));
+  {
+    std::stringstream expected;
+    expected << "Check failed [" << __FILE__ << ':' << __LINE__ + 2
+             << "] 1 not less than " << 1;
```
Comment (skimo-openhub) [inline test/test_check.cc]: Why is the second "1" outside the string (and not the first one)?
Similarly below.

File: tc/autotuner/genetic_search.cc [hunk 5]
```diff
@@ -131,11 +131,11 @@ void dropInvalidConfigurations(GeneticSearch::Population& population) {
...
-  CHECK_LT(numberElites, maxPopulationSize);         \
-  CHECK(mutationRate >= 0 and mutationRate <= 100)   \
+  TC_CHECK_LT(numberElites, maxPopulationSize);         \
+  TC_CHECK(mutationRate >= 0 and mutationRate <= 100)   \
       << "the mutation rate (" << mutationRate       \
       << ") should be in the [0,100] interval";      \
-  CHECK(crossOverRate >= 0 and crossOverRate <= 100) \
+  TC_CHECK(crossOverRate >= 0 and crossOverRate <= 100) \
       << "the crossover (" << crossOverRate          \
       << ") rate should be in the [0,100] interval";
```
Comment (skimo-openhub) [inline tc/autotuner/genetic_search.cc]: reformat

File: tc/autotuner/msg [hunk 6]
```diff
@@ -0,0 +1 @@
+#259 switched from TC function names to using whole TCs (canonicalized) as part of compilation cache keys. However, the final step of the autotuner, that is retrieving the best found options, was not updated and it used just the function name. As a result, an empty optional<CudaMappingOptions> was always returned.
```
Comment (skimo-openhub) [inline tc/autotuner/msg]: what's this?

File: tc/core/cuda/cuda_rtc.cc [hunk 7]
```diff
@@ -20,6 +20,7 @@
 #include <cuda_runtime.h>
 #include <nvrtc.h>
 
+#include "tc/core/check.h"
```
Comment (skimo-openhub) [inline tc/core/cuda/cuda_rtc.cc]: Why only here (and a couple of other places)? Shouldn't every file that uses these calls have this include?

File: tc/core/tensor-inl.h [hunk 8]
```diff
@@ -18,9 +18,10 @@
 #include <algorithm>
 #include <sstream>
 
-#include <glog/logging.h>
+//#include <glog/logging.h>
```
Comment (skimo-openhub) [inline tc/core/tensor-inl.h]: remove instead of commenting out

File: tc/core/check.cc (hunk 1 above)
Comment (ttheodor) [reply tc/core/check.cc]: If the `condition` holds then the strings are not used, it's an "optimization". 

It was present in the rest of `tc_check_*` but I removed it because it didn't feel very useful. I forgot to remove this one.

File: tc/core/check.h (hunk 2 above)
Comment (ttheodor) [reply tc/core/check.h]: There's no need. I'll merge them.

File: test/test_check.cc (hunk 4 above)
Comment (ttheodor) [reply test/test_check.cc]: No reason. I'll fix it.

File: test/test_check.cc (hunk 3 above)
Comment (ttheodor) [reply test/test_check.cc]: Do we still have format checking enabled on CI? If yes, then it will complain.

File: tc/autotuner/msg (hunk 6 above)
Comment (ttheodor) [reply tc/autotuner/msg]: I must have accidentally committed this.

**Comment by ttheodor** [comment]
> Υes.  Complain about what?

This:

> This looks fragile and probably compiler dependent.
> Why can you assume that the reported line number is the last line of
> the macro invocation? Better make sure ASSERT_THROW_WHAT call
> is within a single line in these tests.

**Comment by skimo-openhub** [comment]
On Wed, May 30, 2018 at 06:26:23AM -0700, Theodoros Theodoridis wrote:
> > Υes.  Complain about what?
> 
> This:
> 
> > This looks fragile and probably compiler dependent.
> > Why can you assume that the reported line number is the last line of
> > the macro invocation? Better make sure ASSERT_THROW_WHAT call
> > is within a single line in these tests.

Why would it complain if you arrange for all ASSERT_THROW_WHAT calls
to stay within a line?

skimo

File: tc/core/check.h (hunk 2 above)
Comment (ttheodor) [reply tc/core/check.h]: On a second thought there is one use case:
```
TC_CHECK_X(...) << "A" << "B";
```

What I initially implemented will print the following:
```
Check failed [file:lineno] "what failed": AB
```
The `"what failed"` depends on the type of check, e.g. for `TC_CHECK_EQ(1,2)` it would be `1 not equal to 2`. This part of the output is always present.

Extra information (passed with `<<`) is optional. The reason I keep track of it in a separate string is to figure out if and where the separator (`:`) and the space before it  should be printed. 

There are two options:
1. The optional/extra information is maintained on a separate string.
2. The space and separator is appended on the first call to `operator<<` and there is extra state that keeps track of it (e.g., a boolean).

**Comment by skimo-openhub** [comment]
On Thu, May 31, 2018 at 05:51:53AM -0700, Theodoros Theodoridis wrote:
> Extra information (passed with `<<`) is optional. The reason I keep track of it in a separate string is to figure out if and where the separator (`:`) and the space before it  should be printed. 

OK.

skimo

**Comment by ttheodor** [comment]
All comments were addressed.

**Comment by ttheodor** [comment]
Being able to specify the exception type makes a lot of sense. How about  adding "overloads" with an extra exception type parameter?  For example:
```
CHECK_LT(i,size, std::out_of_range);
```

**Comment by nicolasvasilache** [comment]
@ttheodor sounds good to me but let's do it as a followup PR? No point in delaying landing this nice improvement.

**Comment by ttheodor** [comment]
@nicolasvasilache since this was still unmerged I went ahead and implemented the checks with custom exception types.

**Comment by nicolasvasilache** [comment]
@ttheodor  you should be able to rebase and land this now

**Comment by ttheodor** [comment]
Rebased

**Comment by nicolasvasilache** [comment]
Landing this now without extra reviews because it has been accepted multiple times and ends up being delayed over and over since everything conflicts with it.

File: tc/core/mapping_options-inl.h [hunk 9]
```diff
@@ -161,7 +161,7 @@ MappingOptionsView& MappingOptionsView::scheduleFusionStrategy(
 
 MappingOptionsView& MappingOptionsView::scheduleFusionStrategy(
     const std::string& str) {
-  FusionStrategy fs;
```
Comment (skimo-openhub) [inline tc/core/mapping_options-inl.h]: Who complains about this and why?

Comment (ftynse) [reply tc/core/mapping_options-inl.h]: see #500, I did not understand that either.

Comment (nicolasvasilache) [reply tc/core/mapping_options-inl.h]: see #504 (it should show in the CI)
