### PR TITLE
CudaRTCFunction: do not unload the module that was never loaded

### LINKED ISSUE #292: Autotuner aborts when tuning conv2d
- OS: Ubuntu 16.04
- How you installed TC (docker, conda, source): source
- Python version: 3.5
- CUDA/cuDNN version: 9.1 / 7.1.2
- GCC/GXX version (if compiling from source): 5.4
- LLVM/Tapir git hash used (if compiling from source): 
clang version 5.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/mercy/clang+llvm-tapir5.0/bin
- Commit hash of our repo and submodules (if compiling from source):
https://github.com/facebookresearch/TensorComprehensions/commit/ef644ba7d638f3f8b028f52192101cf1f48b32b4
- Hardware: crashed on both Titan X and 1050Ti

script 
```python
import numpy as np
import torch
import os

import tensor_comprehensions as tc

settings = {
    "threads": 8, "generations": 10, "pop_size": 100, "number_elites": 3
}

conv2d_lang = """
def conv2d(float(N, C, H, W) I, float(M, C, KH, KW) W1) -> (output) {{
    output(n, m, h, w) +=! I(n, c, {sh} * h + kh, {sw} * w + kw) * W1(m, c, kh, kw)
}}
"""

print(os.getpid())

N, H, C, M, KH, sh, pad = 1, 56, 64, 128, 3, 2, 1
H = H + 2 * pad
W = H
KW = KH
sw = sh

conv2d = tc.define(conv2d_lang, name="conv2d", constants={"sh": sh, "sw": sw})

options = tc.Options('conv')
data, kernel = torch.randn(N, C, H, W).cuda(), torch.randn(M, C, KH, KW).cuda()

conv2d.autotune(data, kernel, options=options, **settings)
```

output
```
[WARNING]: Autotuning results won't be cached. 'cache' option is not set
Generation 0	Jobs(Compiled, GPU)/total  (89, 81)/100   (best/median/worst)us: 1183/4122/56294WARNING: Logging before InitGoogleLogging() is written to STDERR
W0411 17:14:07.169371  6574 cuda_rtc.cc:144] Error at: /home/mercy/project/TensorComprehensions/src/core/cuda/cuda_rtc.cc:144: CUDA_ERROR_INVALID_PTX
W0411 17:14:07.169657  6574 genetic_tuning_harness.cc:415] Runtime error gpu 0: Error at: /home/mercy/project/TensorComprehensions/src/core/cuda/cuda_rtc.cc:144: CUDA_ERROR_INVALID_PTX
W0411 17:14:07.169761  6574 genetic_tuning_harness.cc:419] Aborted execution on gpu 0
W0411 17:14:07.169840  6574 genetic_tuning_harness.cc:420] tc::MappingOptions::makeNaiveMappingOptions()
W0411 17:14:07.169909  6574 genetic_tuning_harness.cc:420]     .outerScheduleFusionStrategy(tc::FusionStrategy::Preserve3Coincident)
W0411 17:14:07.169976  6574 genetic_tuning_harness.cc:420]     .outerScheduleAllowSkewing(false)
W0411 17:14:07.170042  6574 genetic_tuning_harness.cc:420]     .outerSchedulePositiveOrthant(true)
W0411 17:14:07.170109  6574 genetic_tuning_harness.cc:420]     .intraTileScheduleFusionStrategy(tc::FusionStrategy::Min)
W0411 17:14:07.170174  6574 genetic_tuning_harness.cc:420]     .intraTileScheduleAllowSkewing(false)
W0411 17:14:07.170239  6574 genetic_tuning_harness.cc:420]     .intraTileSchedulePositiveOrthant(true)
W0411 17:14:07.170306  6574 genetic_tuning_harness.cc:420]     .tile(8, 16, 1)
W0411 17:14:07.170372  6574 genetic_tuning_harness.cc:420]     .unroll(4)
W0411 17:14:07.170436  6574 genetic_tuning_harness.cc:420]     .tileImperfectlyNested(false)
W0411 17:14:07.170503  6574 genetic_tuning_harness.cc:420]     .matchLibraryCalls(true);
W0411 17:14:07.170569  6574 genetic_tuning_harness.cc:420] 
W0411 17:14:07.170635  6574 genetic_tuning_harness.cc:420]     .mapToThreads(29, 15)
W0411 17:14:07.170701  6574 genetic_tuning_harness.cc:420]     .mapToBlocks(3)
W0411 17:14:07.170769  6574 genetic_tuning_harness.cc:420]     .useSharedMemory(true)
W0411 17:14:07.170836  6574 genetic_tuning_harness.cc:420]     .usePrivateMemory(false)
W0411 17:14:07.170902  6574 genetic_tuning_harness.cc:420]     .unrollCopyShared(true);
Generation 0	Jobs(Compiled, GPU)/total  (100, 100)/100   (best/median/worst)us: 1183/4122/56294
W0411 17:14:27.770052  6564 cuda_rtc.cc:44] Error at: /home/mercy/project/TensorComprehensions/src/core/cuda/cuda_rtc.cc:44: CUDA_ERROR_INVALID_HANDLE
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error at: /home/mercy/project/TensorComprehensions/src/core/cuda/cuda_rtc.cc:44: CUDA_ERROR_INVALID_HANDLE
Aborted (core dump)
```

### PR DESCRIPTION
**Pull request by ftynse**
In CudaRTCFunction::Launch, we first add (empty) module to the per-GPU
list of modules, and only then try to load it from PTX. The load part
may fail and throw, the module in the list remaining empty. When the
CudaRTCFunction is destroyed, its destructor tries to unload the module
available in the list. Since the module is empty, unloading fails and
throws. The exception does not seem to be handled, and can even happen
during unwinding of another exception leading to immediate termination.

Load CUmodule and extract CUfunction using local variables, and insert
the values into respective per-GPU lists only when both the loading and
the extraction completed without errors.  If they throw, nothing is
inserted and thus the destructor will not attempt to clean non-existent
objects.

Closes #292

### CODE REVIEW

File: tc/core/cuda/cuda_rtc.cc [hunk 1]
```diff
@@ -138,14 +138,14 @@ Duration CudaRTCFunction::Launch(
...
-    TC_CUDA_DRIVERAPI_ENFORCE(cuModuleGetFunction(
-        &(perGpuKernel_.at(dev)),
-        perGpuModule_.at(dev),
-        specializedName.c_str()));
+    CUmodule module;
+    CUfunction function;
+    TC_CUDA_DRIVERAPI_ENFORCE(
+        cuModuleLoadDataEx(&module, nvrtc_ptx.data(), 0, 0, 0));
+    TC_CUDA_DRIVERAPI_ENFORCE(
+        cuModuleGetFunction(&function, module, specializedName.c_str()));
```
Comment (ttheodor) [inline tc/core/cuda/cuda_rtc.cc]: Don't we need to unload the module if this fails?

Comment (ftynse) [reply tc/core/cuda/cuda_rtc.cc]: Probably, I don't really know why we unload it in the first place.

**Comment by nicolasvasilache** [comment]
Nice catch.

**Comment by ftynse** [comment]
I ran the tests and the reproducer for #292 where I observed that indeed the autotuning continues after `invalid PTX` error without crashing.

**Comment by ttheodor** [comment]
local tests passed
