### PR TITLE
[hotfix] Support min max bounds

### LINKED ISSUE #124: Exception thrown: "isl.h:3185: NULL input thrown in the test body"
one of our user reported an issue with TC
```
def graph2(float(N, C, H, W) I, float(N, C, R, T) J, float(KH, KW) W1) -> (O, Out) {
        O(n, c, h, w) +=! J(n, c, h + kh, w + kw) * W1(kh, kw)
        Out(i, j) +=! I(n, i, h, w) * O(n, j, h, w)
}
```
which consistently throws error:
```
unknown file: Failure
C++ exception with description "/home/prigoyal/local/TensorComprehensions/third-party-install/include/isl/interface/isl.h:3185: NULL input" thrown in the test body.
```

### PR DESCRIPTION
**Pull request by ftynse**
Loop bounds inferred by Halide may involve min or max operations, which
are not convertible into affine functions.  For the sake of bound
computation, compute lists of affine functions by recursively
flattening arguments of nested min and max operations.  Use all
affine functions from a list to define loop bounds.  In particular,
allow min in upper bounds and max in lower bounds to exploit
```
  x < min(a, min(b, c)) <=> x < a and x < b and x < c,
  x > max(a, max(b, c)) <=> x > a and x > b and x > c
```
equivalences.  Do not allow other cases.

Closes #124 #125

### CODE REVIEW

**Comment by prigoyal** [comment]
looks good from my side, can't speak about the halide specific changes but test case looks good to me :) thanks for the quick hotfix, much appreciated :)

File: src/core/halide2isl.cc [hunk 1]
```diff
@@ -82,44 +82,141 @@ isl::aff makeIslAffFromInt(isl::space space, int64_t val) {
...
+  const Max* maxOp = e.as<Max>();
+
   if (const Variable* op = e.as<Variable>()) {
     isl::local_space ls = isl::local_space(space);
     int pos = space.find_dim_by_name(isl::dim_type::param, op->name);
     if (pos >= 0) {
-      return isl::aff(ls, isl::dim_type::param, pos);
+      return {isl::aff(ls, isl::dim_type::param, pos)};
     } else {
+      // FIXME: thou shalt not rely upon set dimension names
```
Comment (abadams) [inline src/core/halide2isl.cc]: Halide references all dimensions by name, so the only alternative here is to also pass a map from name to set dimension index along with every Expr that we may want to turn into an isl:aff.... Except the isl::space can already *be* that map for us if we set up the names correctly.

Comment (ftynse) [reply src/core/halide2isl.cc]: I'm just leaving a comment in the code before @skimo-openhub complains...

File: src/core/halide2isl.cc [hunk 2]
```diff
@@ -82,44 +82,141 @@ isl::aff makeIslAffFromInt(isl::space space, int64_t val) {
...
-        return isl::aff(ls, isl::dim_type::set, pos);
+        return {isl::aff(ls, isl::dim_type::set, pos)};
       }
     }
     LOG(FATAL) << "Variable not found in isl::space: " << space << ": " << op
                << ": " << op->name << '\n';
-    return isl::aff();
+    return {};
+  } else if (minOp != nullptr && allowMin) {
+    return concatAffs(space, minOp, allowMin, allowMax);
```
Comment (abadams) [inline src/core/halide2isl.cc]: Once you've allowed a min, should allowMax still be true? What happens with x < max(min(max(min(....))))

Comment (ftynse) [reply src/core/halide2isl.cc]: The trick with multiple constraints does not work, so it should not be allowed.  There's a check above that allowMin and allowMax should not be true at the same time.

Comment (abadams) [reply src/core/halide2isl.cc]: Ah, didn't see that check

File: src/core/halide2isl.cc [hunk 3]
```diff
@@ -82,44 +82,141 @@ isl::aff makeIslAffFromInt(isl::space space, int64_t val) {
...
+ * expression.
+ * If a Halide expression cannot be converted into a list of affine expressions,
+ * return an empty list.
+ */
+std::vector<isl::aff> makeIslAffBoundsFromExpr(
+    isl::space space,
+    const Expr& e,
+    bool allowMin,
+    bool allowMax) {
+  CHECK(!(allowMin && allowMax));
```
Comment (nicolasvasilache) [inline src/core/halide2isl.cc]: Feels like this could actually happen with reasonable combinations of positive and negative indices.
In which case maybe this should be reported as a user-facing TC well-formedness error but scorch the earth via CHECK is too aggressive?

File: test/test_tc_mapper_bugs.cc [hunk 4]
```diff
@@ -696,6 +696,25 @@ TEST(LayerNorm, ReferenceBelongsToTwoGroups) {
   atCompl.compile("layernorm", inputs, options);
 }
 
+TEST(Halide2Isl, MinInUpperBound) {
```
Comment (nicolasvasilache) [inline test/test_tc_mapper_bugs.cc]: Looks a bit light on the testing side, could wee see stuff with strides and constants such that ```gcd(x.y)==1``` to shake off a little bit more the different paths added in this PR (in particular ```div```)?
Is there anything we can do to "expect" that we get a combination of ```min``` or ```max``` and ```div```?

File: src/core/halide2isl.cc [hunk 5]
```diff
@@ -82,44 +82,141 @@ isl::aff makeIslAffFromInt(isl::space space, int64_t val) {
...
+ * expression.
+ * This is intended for use with operations other than Min/Max that do not
+ * commute nicely in bounds, for example
+ *   x < a + max(b,c)  NOT <=>  x < a + b AND x < a + c for negative values.
+ */
+template <typename T>
+inline isl::aff combineSingleAffs(
+    isl::space space,
+    T op,
+    isl::aff (isl::aff::*combine)(isl::aff) const) {
```
Comment (nicolasvasilache) [inline src/core/halide2isl.cc]: quickly eyeballing I can't figure out easily what this ```isl::aff::*combine``` is, care to explain briefly?

File: src/core/halide2isl.cc [hunk 6]
```diff
@@ -82,44 +82,141 @@ isl::aff makeIslAffFromInt(isl::space space, int64_t val) {
...
+ * converting its LHS and RHS into lists of affs and concatenating those lists.
+ * This is intended to be used with Min/Max operations in upper/lower bound
+ * computations, respectively.  Essentially, this allows for replacements
+ *   x < min(a,min(b,c)) <=> x < a AND x < b AND x < c
+ *   x > max(a,max(b,c)) <=> x > a AND x > b AND x > c
+ */
+template <typename T>
+inline std::vector<isl::aff>
+concatAffs(isl::space space, T op, bool allowMin, bool allowMax) {
+  std::vector<isl::aff> result;
```
Comment (nicolasvasilache) [inline src/core/halide2isl.cc]: Optionally you could write it this way with a proper ```operator+=```, but not worth changing, just mentioning.
```
std::vector<isl::aff> result(makeIslAffBoundsFromExpr(space, op->a, allowMin, allowMax));
results += makeIslAffBoundsFromExpr(space, op->b, allowMin, allowMax);
return result;
```

**Comment by ftynse** [comment]
This is a hotfix, better solution requires constructing pw affs and sets
from those and looked more involved.

**Comment by prigoyal** [comment]
Hi @ftynse , would you like to have this PR merged ? or wait out to implement permanent solution :) either is fine by me, just wanted to check on the status :)

File: src/core/halide2isl.cc (hunk 3 above)
Comment (ftynse) [reply src/core/halide2isl.cc]: This particular function and the approach it implements does not support any combination of min/max in the same expression.  You are not supposed to call it with both `allowMin` and `allowMax`, so it is better to kill the run early.  It will _not_ kill the run if there is a min/max combo in the inferred bounds because we never call it the way that fails the check. 

There is another check below that will kill everything.  Before, we would report a cryptic error from isl and die anyway, so this is an improvement IMO.

File: test/test_tc_mapper_bugs.cc (hunk 4 above)
Comment (ftynse) [reply test/test_tc_mapper_bugs.cc]: This patchset intends to hotfix the problem reported in #124 hence the test.

> Is there anything we can do to "expect" that we get a combination of min or max and div?

I'm actually not sure if we can get `max` because we always start tensor subscripts at zero...

File: src/core/halide2isl.cc (hunk 6 above)
Comment (ftynse) [reply src/core/halide2isl.cc]: Yes, considered that but decided that `+=` in the context where we operate on affine functions with another overloaded `operator+` can be misleading.

**Comment by ftynse** [comment]
@prigoyal as I told online, this is a quickfix for #124 reported by a user.  I know this is a limited solution.  I was expecting it to get merged the same day.  If somebody has resources to implement the proper solution, please go ahead, submit a PR and close this.  I'm fine either way.

**Comment by prigoyal** [comment]
thanks, I have no preferences. Hotfix is fine but this is also not super urgent.

**Comment by ftynse** [comment]
Strange. All other user reported bugs were considered urgent.

**Comment by prigoyal** [comment]
@ftynse, I didn't make my wording clear. I didn't mean that this is not an important feature but I meant that this is more of a feature not bug [IMO]. User has been given the workaround they are using atm. So this will be part of next package releases in 1 month and we don't need to merge it quickly and rather we can spend time on finding better solution if that's the preference.  hope that clarifies :)

**Comment by prigoyal** [comment]
cc @hmansell
